// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIshX20cj-ul9ot1VGlFTfMY0WbEi0iR8',
    appId: '1:1013004696091:web:59619804fcff58503156be',
    messagingSenderId: '1013004696091',
    projectId: 'programacion-movil-q2',
    authDomain: 'programacion-movil-q2.firebaseapp.com',
    storageBucket: 'programacion-movil-q2.firebasestorage.app',
    measurementId: 'G-EHZTLRZSEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC0NW88iIJRkgHxjKOODnnQDdGd_JIpr4',
    appId: '1:1013004696091:android:3467b0eabdac55b83156be',
    messagingSenderId: '1013004696091',
    projectId: 'programacion-movil-q2',
    storageBucket: 'programacion-movil-q2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5zpxOc5fgry8TiIbTCED3lFXgyzgp60',
    appId: '1:1013004696091:ios:390802359b263c293156be',
    messagingSenderId: '1013004696091',
    projectId: 'programacion-movil-q2',
    storageBucket: 'programacion-movil-q2.firebasestorage.app',
    iosClientId: '1013004696091-0igldh8od3uuc4uio0cre3lh784f9sls.apps.googleusercontent.com',
    iosBundleId: 'com.example.appClase',
  );

}